namespace: ci-operator
name: rudder
version: 0.0.1
readme: README.md
authors:
  - josiah@redhat.com
description: Helm chart preprocessor
issues: https://github.com/ci-operator/rudder/issues
repository:
  https://github.com/ci-operator/rudder.git
build_ignore: 
  - build
  - install
  - '*.tar.gz'
  - '*~'
